baseURL = '/'
languageCode = 'en'
defaultContentLanguage = "en"
hasCJKLanguage = true
title = 'edrys-Lite [BLOG]'
copyright = 'The erdys-Lite Team'
theme = 'itheme'

timeZone = "Europe/Berlin"

[pagination]
pagerSize = 5

[params]
defaultCover = 'https://www.apple.com.cn/newsroom/images/apple-logo_black.jpg.landing-regular_2x.jpg'
email = 'andre.dietrich@informatik.tu-freiberg.de'
[[params.socialMedia]]
name = 'Github'
url = 'https://github.com/edrys-labs'
#[[params.socialMedia]]
#name = 'Twitter'
#url = 'https://twitter.com/some-one'
[[params.blogroll]]
name = 'edrys-Lite'
url = 'https://edrys-labs.github.io'
[[params.blogroll]]
name = 'LiaScript'
url = 'https://LiaScript.github.io'


[markup.goldmark.renderer]
unsafe = true
